@baseURL= http://localhost:3333
@authToken= {{authenticate.response.body.access_token}}
@recipientId= {{register_recipient_account.response.body.recipientId.value}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@gmail.com",
  "cpf": "1",
  "password": "123456",
  "role": "ADM"
}

###

# @name register_deliveryman_account
POST {{baseURL}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Gabriel Deliveryman",
  "email": "gabrielDelvieryman@gmail.com",
  "cpf": "2",
  "password": "123456",
  "role": "DELIVERYMAN"
}

###

# @name register_recipient_account
POST {{baseURL}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Gabriel",
  "email": "gabriel97@gmail.com",
  "cpf": "3"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "cpf": "2",
  "password": "123456"
}

###

# @name get_account_profile
GET {{baseURL}}/account/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

####

# @name edit_account
PUT {{baseURL}}/account/edit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "gabriel Delvier",
  "email": "edit email account"
}

###

# @name delete_account
DELETE {{baseURL}}/account/profile?accountID={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_address
POST {{baseURL}}/recipients/addresses
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "recipientId": "{{recipientId}}",
  "city": "Labrea",
  "street": "Rua palmares",
  "houseNumber": "number-1",
  "latitude": -7.267809,
  "longitude": -64.794920
}

###

# @name create_order
POST {{baseURL}}/orders?recipientId={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "addressId": "1ac429b6-cd0e-4ebc-a453-341d3aadc788" 
}

###

# @name get_order
GET {{baseURL}}/orders/d1c21628-ec10-4867-b079-54aed514fd72/{{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name order_available
PUT {{baseURL}}/orders/available/d1c21628-ec10-4867-b079-54aed514fd72/{{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name order_picked_up
PUT {{baseURL}}/orders/pickedUp/d1c21628-ec10-4867-b079-54aed514fd72/a943da79-8dd3-42aa-bb10-549df0f20e02
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name deliver_order
PUT {{baseURL}}/orders/delivered/d1c21628-ec10-4867-b079-54aed514fd72/{{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "attachments": [
    "id-one",
    "id-two"
  ]
}

###

# @name delete_order
DELETE {{baseURL}}/orders?orderId=8ff648c9-89c0-4ffb-8ce4-41b1f22fbe39
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_deliveryman_orders
GET {{baseURL}}/orders/deliveryman
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_recipient_orders
GET {{baseURL}}/orders/recipient?page=1&recipientId={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_orders_nearby
GET {{baseURL}}/orders/nearby
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "latitude": -7.266294,
  "longitude": -64.797787
}

###

# @name read_Notification
PATCH {{baseURL}}/notifications/:notificationId/read/{{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{}

###






