@baseURL= http://localhost:3333
@authToken= {{authenticate.response.body.access_token}}
@recipientId= {{create_recipient_account.response.body.recipientId.value}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@gmail.com",
  "cpf": "1234567",
  "password": "123456",
  "role": "ADM"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "cpf": "1234567",
  "password": "123456"
}

###

# @name get_account_profile
GET {{baseURL}}/account/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

####

# @name delete_account
DELETE {{baseURL}}/account/profile?accountID={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_recipient_account
POST {{baseURL}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Gabriel",
  "email": "gabriel97@gmail.com",
  "cpf": "12345678"
}

###

# @name create_address
POST {{baseURL}}/recipients/addresses
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "recipientId": "{{recipientId}}",
  "city": "Labrea",
  "street": "Rua palmares",
  "houseNumber": "number-1",
  "latitude": 7.255565,
  "longitude": 64.789486
}

###

# @name create_order
POST {{baseURL}}/orders?recipientId={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
// precisa add o id do address aqui!
{
  "addressId": "873469c8-659e-49b6-aaf9-1f2864060092", 
  "pickupAvailableOrder": "2023-8-22"
}

###

# @name delete_order
DELETE {{baseURL}}/orders?orderId=37d6f989-7387-473c-91e1-e996fd8ec388
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_deliveryman_orders
GET {{baseURL}}/orders/deliveryman
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_recipient_orders
GET {{baseURL}}/orders/recipient?page=1&recipientId={{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###



