@baseURl= http://localhost:3333
@authToken= {{{{authenticate.response.body.access_token}}}}

# @name create_account
POST {{baseURl}}/accounts
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@gmail.com",
  "cpf": "123456",
  "password": "124356"
}

###

# @name authenticate
POST {{baseURl}}/authenticate
Content-Type: application/json

{
  "email": "gabriel@gmail.com",
  "password": "124356"
}
